version: '3'
services:
  fastapi:
    image: %DOCKER_REGISTRY_USER%/%PROJECT_NAME%:%TAG%
    ports:
      - "8000:8000"
    restart: always

  flask:
    image: %DOCKER_REGISTRY_USER%/%FLASK_NAME%:%TAG%
    environment:
      IP_API: '%SERVER_IP%'
    ports:
      - "80:5000"
    restart: always
